### ISSUE TITLE
aws lambda template

### ISSUE THREAD

**Issue by izifortune** [0x13a/bitcoin-trading-dca#7]
Hi @0x13a thanks for your work on this project.
I've been using your project for a while and unfortunately aws lambda doesn't support async/await
yet, so i've created a template using serverless stack https://serverless.com to make it easier to deploy it to aws.

You can have a look here https://github.com/izifortune/bitcoin-trading-dca-serverless

Hope that we can collaborate on this.

**Comment by 0x13a** [comment]
Hi @izifortune thanks for porting your project to serverless!
I really like the idea of serverless, but I don't like the idea of being  AWS Lambda-dependent. Anyway thanks for your work, I will use for my next experiments. Feel free to link your project in the readme.md file if you like to.

Best,

**Comment by izifortune** [comment]
I totally understand that you don't want this AWS dependent.
I was thinking more of abstracting the core functionality away from the file system/console logging, so that can be reused directly ( without copying it ).
I have some ideas i will be in touch :)

**Comment by 0x13a** [comment]
fixed in https://github.com/0x13a/bitcoin-trading-dca/pull/8
